modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-Autumnity/issues"

[[mods]]
modId="dtautumnity"
version="${file.jarVersion}"
displayName="Dynamic Trees for Autumnity"

updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Autumnity.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-autumnity"

authors="Max Hyper"
description='''
Compatibility Mod between Dynamic trees and Autumnity
'''
[[dependencies.dtautumnity]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtautumnity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtautumnity]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtautumnity]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtautumnity]]
    modId="autumnity"
    mandatory=true
    versionRange="[2.1.2,)"
    ordering="AFTER"
    side="BOTH"
